"""
Experiment 017 — dinucleotide-Markov negatives.

Composition (50K total):
- 25K positives: 15K uniform cCRE + 5K CTCF + 5K DNH3 (same as 013)
- 25K dinucleotide-Markov negatives: each generated by sampling from
  the GLOBAL dinucleotide transition matrix computed from positives.
  Same length (200bp), same dinucleotide statistics on average,
  but no real motifs.

Hypothesis: paired flanks (013) work because they're informative
geographic negatives. Dinucleotide-Markov negatives are a different
flavor: composition-matched but motif-free. If the model is learning
mainly via composition shortcuts, Markov negatives will hurt eval
(no signal). If it's learning motifs, Markov negatives may HELP or
match 013 by forcing pure motif discrimination.

Predicted: similar to 013 or slightly worse. The interest is in the
PATTERN of wins/losses — which evals reward motif-only learning?
"""
import os, time, numpy as np

L = 200
HALF = L // 2
SEED = 0

N_UNIFORM = 15_000
N_CTCF = 5_000
N_DNH3 = 5_000
N_POS = N_UNIFORM + N_CTCF + N_DNH3  # 25000

def classify_rare(type_str):
    parts = set(t.strip() for t in type_str.split(","))
    if "DNase-H3K4me3" in parts: return "DNH3"
    if "CTCF-only" in parts: return "CTCF"
    return None

def main():
    here = os.path.dirname(__file__)
    repo_root = os.path.abspath(os.path.join(here, "..", ".."))
    cache_dir = os.path.join(repo_root, "data", "hg38_npy")
    bed_path = os.path.join(repo_root, "data", "GRCh38-cCREs.bed")
    t0 = time.time()

    genome, n_prefix = {}, {}
    for f in sorted(os.listdir(cache_dir)):
        if f.endswith(".npy"):
            c = f[:-4]
            mat = np.asarray(np.load(os.path.join(cache_dir, f), mmap_mode="r"))
            genome[c] = mat
            is_n = (mat == ord("N")).astype(np.int32)
            n_prefix[c] = np.concatenate(([0], np.cumsum(is_n)))
    chroms = sorted(genome.keys())
    print(f"genome+prefix in {time.time()-t0:.1f}s")
    bases = set("ACGT")
    rng = np.random.default_rng(SEED)

    # Sample 013-style positives (no flanks).
    all_mids, ctcf_mids, dnh3_mids = [], [], []
    with open(bed_path) as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            c = parts[0]
            if c not in genome: continue
            s, e = int(parts[1]), int(parts[2])
            mid = (s + e) // 2
            all_mids.append((c, mid))
            bk = classify_rare(parts[5])
            if bk == "CTCF": ctcf_mids.append((c, mid))
            elif bk == "DNH3": dnh3_mids.append((c, mid))
    print(f"  total={len(all_mids):,}  CTCF={len(ctcf_mids):,}  DNH3={len(dnh3_mids):,}")

    def sample_pos(items, need, label):
        order = rng.permutation(len(items))
        out = []
        for j in order:
            c, mid = items[j]
            s = mid - HALF
            if s < 0 or s + L > len(genome[c]): continue
            if n_prefix[c][s + L] - n_prefix[c][s] != 0: continue
            w = genome[c][s:s + L].tobytes().decode("ascii")
            if set(w) <= bases:
                out.append(w)
            if len(out) >= need: break
        print(f"  {label}: {len(out)}")
        return out

    positives = []
    positives += sample_pos(all_mids, N_UNIFORM, "uniform")
    positives += sample_pos(ctcf_mids, N_CTCF, "CTCF")
    positives += sample_pos(dnh3_mids, N_DNH3, "DNH3")
    assert len(positives) == N_POS

    # Compute global dinucleotide transition matrix from positives.
    bases_str = "ACGT"
    b2i = {b: i for i, b in enumerate(bases_str)}
    trans = np.zeros((4, 4), dtype=np.float64)
    for s in positives:
        arr = np.frombuffer(s.encode("ascii"), dtype=np.uint8)
        idx = np.array([b2i[chr(c)] for c in arr], dtype=np.int8)
        prev = idx[:-1]; nxt = idx[1:]
        for a, b in zip(prev, nxt):
            trans[a, b] += 1
    row_sums = trans.sum(axis=1, keepdims=True)
    P = trans / row_sums  # row-stochastic
    init_p = trans.sum(axis=0)  # initial = stationary-ish
    init_p = init_p / init_p.sum()
    print(f"  dinucleotide transition matrix:\n{P.round(3)}")

    # Generate 25K Markov negatives, vectorized.
    # For each negative: start from sampled base, then walk.
    n_neg = N_POS
    cdf = np.cumsum(P, axis=1)
    init_cdf = np.cumsum(init_p)
    starts = np.searchsorted(init_cdf, rng.random(n_neg))
    seqs_idx = np.zeros((n_neg, L), dtype=np.int8)
    seqs_idx[:, 0] = starts
    rand_mat = rng.random((n_neg, L - 1))
    for i in range(L - 1):
        cur = seqs_idx[:, i]
        r = rand_mat[:, i]
        # next = first column j where cdf[cur, j] > r
        seqs_idx[:, i + 1] = (cdf[cur] > r[:, None]).argmax(axis=1)
    bases_arr = np.array(list(bases_str), dtype="U1")
    neg_seqs = bases_arr[seqs_idx]
    negatives = ["".join(row) for row in neg_seqs]
    print(f"  generated {len(negatives)} dinuc-Markov negatives")
    assert len(negatives) == n_neg

    all_seqs = positives + negatives
    perm = rng.permutation(len(all_seqs))
    all_seqs = [all_seqs[i] for i in perm]
    assert len(all_seqs) == 50_000

    out_path = os.path.join(here, "sequences_0.txt")
    with open(out_path, "w") as f:
        for s in all_seqs:
            f.write(s); f.write("\n")
    gc = sum(1 for s in all_seqs[:5000] for c in s if c in "GC") / (5000 * L)
    print(f"wrote 50000 → {out_path} (GC {gc:.3f}, total {time.time()-t0:.1f}s)")

if __name__ == "__main__":
    main()
