"""Experiment 023: variant-perturbed natural (paired SNP variants).

12.5K natural + 12.5K natural-5SNPs + 10K cCRE off + 5K cCRE-5SNPs +
5K DHS + 5K mouse = 50K.

Each "variant" sequence is generated by taking a base sequence and
introducing 5 random point mutations (5/200 = 2.5% substitution rate).
The library thus contains 17.5K matched (original, variant) pairs.

Hypothesis: the model benefits from paired data with similar sequences
and (possibly) similar activity. Teaches motif sensitivity — a SNP in
a motif kills activity, a SNP in a spacer doesn't.

If 023 > 0.508: paired-variant supervision helps.
If equal: model doesn't extract paired structure (just sees them as
independent training examples). Plateau holds.
"""
import gzip
import os

import numpy as np
from pyfaidx import Fasta

N_SEQ = 50_000
N_NATURAL = 12_500
N_NATURAL_VAR = 12_500
N_CCRE = 10_000
N_CCRE_VAR = 5_000
N_DHS = 5_000
N_MOUSE = N_SEQ - N_NATURAL - N_NATURAL_VAR - N_CCRE - N_CCRE_VAR - N_DHS
L = 200
SEED = 0
SNPS_PER = 5

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
HG38 = os.path.join(REPO_ROOT, "data", "hg38.fa")
MM39 = os.path.join(REPO_ROOT, "data", "mm39.fa")
CCRE = os.path.join(REPO_ROOT, "data", "ccre.bed.gz")
DHS = os.path.join(REPO_ROOT, "data", "dhs_index.tsv.gz")

HUMAN_CHROMS = [f"chr{i}" for i in range(1, 23)] + ["chrX", "chrY"]
MOUSE_CHROMS = [f"chr{i}" for i in range(1, 20)] + ["chrX", "chrY"]
HUMAN_SET = set(HUMAN_CHROMS)
HIGH_CONF = {"PLS", "pELS", "dELS", "CA-TF", "CA-CTCF"}

BASES = ["A", "C", "G", "T"]


def perturb(s, n_snps, rng):
    """Introduce n_snps random point mutations (substitutions to a
    different base)."""
    positions = rng.choice(len(s), size=n_snps, replace=False)
    seq = list(s)
    for p in positions:
        orig = seq[p]
        new = rng.choice([b for b in BASES if b != orig])
        seq[p] = new
    return "".join(seq)


def sample_natural(fa, chroms, n, rng):
    chrom_lens = {c: len(fa[c]) for c in chroms}
    arr = np.array(chroms)
    weights = np.array([chrom_lens[c] for c in chroms], dtype=np.float64)
    weights /= weights.sum()
    out = []
    while len(out) < n:
        c = rng.choice(arr, p=weights)
        start = int(rng.integers(0, chrom_lens[c] - L))
        s = str(fa[c][start:start + L]).upper()
        if "N" in s or len(s) != L:
            continue
        out.append(s)
    return out


def sample_offcenter_ccre(fa, n, rng):
    elements = []
    with gzip.open(CCRE, "rt") as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if parts[0] not in HUMAN_SET or parts[9] not in HIGH_CONF:
                continue
            mid = (int(parts[1]) + int(parts[2])) // 2
            elements.append((parts[0], mid))
    idx = rng.permutation(len(elements))
    out = []
    for i in idx:
        chrom, mid = elements[i]
        offset = int(rng.integers(25, 176))
        start = mid - offset
        end = start + L
        if start < 0 or end > len(fa[chrom]):
            continue
        s = str(fa[chrom][start:end]).upper()
        if "N" in s or len(s) != L:
            continue
        out.append(s)
        if len(out) >= n:
            break
    return out


def sample_dhs(fa, n, rng):
    summits = []
    with gzip.open(DHS, "rt") as f:
        next(f)
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if parts[0] not in HUMAN_SET:
                continue
            summits.append((parts[0], int(parts[6])))
    idx = rng.permutation(len(summits))
    out = []
    for i in idx:
        chrom, mid = summits[i]
        start = mid - L // 2
        end = start + L
        if start < 0 or end > len(fa[chrom]):
            continue
        s = str(fa[chrom][start:end]).upper()
        if "N" in s or len(s) != L:
            continue
        out.append(s)
        if len(out) >= n:
            break
    return out


def main():
    hg = Fasta(HG38, sequence_always_upper=True)
    mm = Fasta(MM39, sequence_always_upper=True)
    rng = np.random.default_rng(SEED)
    natural = sample_natural(hg, HUMAN_CHROMS, N_NATURAL, rng)
    nat_var = [perturb(s, SNPS_PER, rng) for s in natural[:N_NATURAL_VAR]]
    ccre = sample_offcenter_ccre(hg, N_CCRE, rng)
    ccre_var = [perturb(s, SNPS_PER, rng) for s in ccre[:N_CCRE_VAR]]
    dhs = sample_dhs(hg, N_DHS, rng)
    mouse = sample_natural(mm, MOUSE_CHROMS, N_MOUSE, rng)
    seqs = natural + nat_var + ccre + ccre_var + dhs + mouse
    rng.shuffle(seqs)
    assert len(seqs) == N_SEQ
    out = os.path.join(os.path.dirname(__file__), "sequences_0.txt")
    with open(out, "w") as f:
        f.write("\n".join(seqs))
        f.write("\n")
    print(f"wrote {N_SEQ}: nat={len(natural)} nat_var={len(nat_var)} "
          f"ccre={len(ccre)} ccre_var={len(ccre_var)} dhs={len(dhs)} mouse={len(mouse)}")


if __name__ == "__main__":
    main()
