"""
world.py — The genetic code layer.

A WORLD is a counterfactual biology. It is defined by:
  - alphabet_size : number of "bases" (Earth: 4)
  - codon_length  : bases per codon (Earth: 3)
  - a codon -> {H, P} map

The agent submits DNA over the alphabet. The world translates DNA into an
H/P residue chain. The residue chain folds (in hp_fold / the C table) to a
fitness. The world is the ONLY thing that varies between experiments; the
folding physics underneath is fixed and shared.

Every world is generated by ONE committed procedure so no world is hand-tuned:
given (alphabet_size, codon_length, structure_spec, h_fraction, seed), the
codon->HP map is produced deterministically. The structure_spec controls WHICH
codon positions are allowed to influence the residue, which is how we build the
positional-discovery worlds (Family 3) with truly silent positions.

Each world also exposes a STRUCTURED GROUND TRUTH describing its true code,
used by the grader to check what the agent figured out. We know this for free
at construction time.
"""

from dataclasses import dataclass, field
from itertools import product
from typing import Callable, Dict, List, Optional, Tuple
import hashlib


# Alphabet letters (supports up to 8 bases cleanly).
_ALPHABET = "ABCDEFGH"


def _det_rng(seed_str: str) -> Callable[[], float]:
    """A tiny deterministic PRNG seeded by a string, so worlds are fully
    reproducible without depending on global RNG state. Returns a function
    yielding floats in [0,1)."""
    state = int(hashlib.sha256(seed_str.encode()).hexdigest(), 16)
    def nxt() -> float:
        nonlocal state
        # xorshift-ish on a big int, take top bits
        state = (state * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        return ((state >> 11) & ((1 << 53) - 1)) / float(1 << 53)
    return nxt


@dataclass
class World:
    name: str
    alphabet_size: int
    codon_length: int
    # codon (tuple of ints, each in [0, alphabet_size)) -> 'H' or 'P'
    code: Dict[Tuple[int, ...], str]
    # structured ground truth for grading
    determining_positions: List[int]      # which codon positions affect the residue
    h_fraction_target: float
    seed: str
    # derived
    alphabet: str = field(init=False)

    def __post_init__(self):
        self.alphabet = _ALPHABET[: self.alphabet_size]

    # ---- translation ----

    def is_valid_dna(self, dna: str) -> Tuple[bool, str]:
        """Check a DNA string is well-formed for this world."""
        if len(dna) % self.codon_length != 0:
            return False, (f"length {len(dna)} not a multiple of codon_length "
                           f"{self.codon_length}")
        bad = set(dna) - set(self.alphabet)
        if bad:
            return False, f"characters {sorted(bad)} not in alphabet {self.alphabet}"
        return True, ""

    def translate(self, dna: str) -> str:
        """DNA string -> H/P residue chain. Assumes already validated."""
        L = self.codon_length
        residues = []
        for i in range(0, len(dna), L):
            codon = tuple(self.alphabet.index(c) for c in dna[i:i + L])
            residues.append(self.code[codon])
        return "".join(residues)

    def residue_length_for(self, dna: str) -> int:
        return len(dna) // self.codon_length


def make_world(
    name: str,
    alphabet_size: int,
    codon_length: int,
    determining_positions: Optional[List[int]] = None,
    interaction: bool = False,
    h_fraction: float = 0.5,
    seed: str = "world-seed",
    seed_id: Optional[str] = None,
) -> World:
    """
    Build a world by the committed procedure.

    determining_positions:
        Which codon positions (0-indexed) actually influence the residue.
        Default: all positions. To make a SILENT position, omit it from this
        list — codons differing only in silent positions map to the SAME
        residue (true synonymity).

    interaction:
        If False, the residue is decided by a per-position scoring rule summed
        over determining positions (additive/composition-like).
        If True, the residue is decided by a JOINT function of the determining
        positions (non-additive) — strictly harder to discover.

    h_fraction:
        Target fraction of residues that are H, enforced approximately by the
        assignment threshold.
    """
    if determining_positions is None:
        determining_positions = list(range(codon_length))
    determining_positions = sorted(determining_positions)
    # seed_id pins the deterministic RNG state independently of the display
    # name, so a world can be renamed without changing its H/P table. Defaults
    # to name for forward-compat; pre-existing worlds preserve their original
    # seed_id in build_catalogue() so historical grades stay valid.
    sid = seed_id if seed_id is not None else name
    rng = _det_rng(f"{seed}|{sid}|{alphabet_size}|{codon_length}|"
                   f"{determining_positions}|{interaction}|{h_fraction}")

    all_codons = list(product(range(alphabet_size), repeat=codon_length))

    code: Dict[Tuple[int, ...], str] = {}

    if not interaction:
        # Additive rule: assign a random weight to each (position, base) but ONLY
        # for determining positions. A codon's score is the sum of weights over
        # determining positions. Threshold the score so ~h_fraction are H.
        weights = {}
        for pos in determining_positions:
            for base in range(alphabet_size):
                weights[(pos, base)] = rng()
        scores = {}
        for codon in all_codons:
            s = sum(weights[(pos, codon[pos])] for pos in determining_positions)
            scores[codon] = s
        # choose threshold to hit h_fraction
        ordered = sorted(scores.values())
        k = int(round((1 - h_fraction) * len(ordered)))
        k = min(max(k, 0), len(ordered) - 1)
        thresh = ordered[k]
        for codon in all_codons:
            code[codon] = 'H' if scores[codon] >= thresh else 'P'
    else:
        # Interaction rule: assign H/P to each COMBINATION of determining-position
        # bases jointly (a lookup over the projected sub-codon), random, balanced
        # to ~h_fraction. Non-determining positions are ignored -> silent.
        combos = list(product(range(alphabet_size), repeat=len(determining_positions)))
        combo_label = {}
        # assign randomly then rebalance toward h_fraction
        vals = [(c, rng()) for c in combos]
        vals.sort(key=lambda t: t[1])
        n_h = int(round(h_fraction * len(vals)))
        for idx, (c, _) in enumerate(vals):
            combo_label[c] = 'H' if idx < n_h else 'P'
        for codon in all_codons:
            key = tuple(codon[pos] for pos in determining_positions)
            code[codon] = combo_label[key]

    return World(
        name=name,
        alphabet_size=alphabet_size,
        codon_length=codon_length,
        code=code,
        determining_positions=determining_positions,
        h_fraction_target=h_fraction,
        seed=seed,
    )


def code_summary(world: World) -> dict:
    """The structured ground truth, for the grader."""
    n_codons = len(world.code)
    n_h = sum(1 for v in world.code.values() if v == 'H')
    # measure actual synonymity: group codons by residue
    return {
        "name": world.name,
        "alphabet_size": world.alphabet_size,
        "codon_length": world.codon_length,
        "determining_positions": world.determining_positions,
        "silent_positions": [p for p in range(world.codon_length)
                             if p not in world.determining_positions],
        "n_codons": n_codons,
        "n_H_codons": n_h,
        "n_P_codons": n_codons - n_h,
        "actual_h_fraction": round(n_h / n_codons, 4),
    }


# ---- The world catalogue: the experiment design as code ----

def build_catalogue(seed: str = "hpbox-2026") -> Dict[str, World]:
    """
    The 8-world catalogue. Each world varies one structural parameter from
    the earthlike baseline. Residue length (N=16) is fixed elsewhere; these
    only define the code layer.

    Note: every make_world call passes `seed_id` set to the world's ORIGINAL
    name (the "F*_..." identifiers these worlds were first registered under).
    The seed_id pins the deterministic H/P-table generation, so renaming the
    display key does not change the world's underlying H/P assignment. Do not
    edit seed_id values — that would silently regenerate the codon table and
    invalidate any prior grading against this catalogue.
    """
    worlds = {}

    # Codon-length variations at alphabet 4
    worlds["codon2"] = make_world(
        "codon2", alphabet_size=4, codon_length=2, seed=seed, seed_id="F1_len2")
    worlds["earthlike"] = make_world(
        "earthlike", alphabet_size=4, codon_length=3, seed=seed, seed_id="F0_earthlike")
    worlds["codon4"] = make_world(
        "codon4", alphabet_size=4, codon_length=4, seed=seed, seed_id="F1_len4")

    # Alphabet-size variations at codon length 3
    worlds["alpha6"] = make_world(
        "alpha6", alphabet_size=6, codon_length=3, seed=seed, seed_id="F2_alpha6")
    worlds["alpha8"] = make_world(
        "alpha8", alphabet_size=8, codon_length=3, seed=seed, seed_id="F2_alpha8")

    # Positional structure (alphabet 4, codon length 3)
    # pos1_only: only the middle position determines residue; flanks are silent
    worlds["pos1_only"] = make_world(
        "pos1_only", alphabet_size=4, codon_length=3,
        determining_positions=[1], seed=seed, seed_id="F3a_pos1_only")
    # pos02_interact: flanks (positions 0, 2) jointly determine residue
    # (non-additive interaction); middle position is silent
    worlds["pos02_interact"] = make_world(
        "pos02_interact", alphabet_size=4, codon_length=3,
        determining_positions=[0, 2], interaction=True, seed=seed,
        seed_id="F3b_pos02_interaction")

    # Full "alien" world: alphabet 6, codon length 4, 3-position interaction,
    # one silent position
    worlds["alien"] = make_world(
        "alien", alphabet_size=6, codon_length=4,
        determining_positions=[0, 2, 3], interaction=True, seed=seed,
        seed_id="F5_alien")

    return worlds


if __name__ == "__main__":
    cat = build_catalogue()
    print(f"{len(cat)} worlds defined:\n")
    for name, w in cat.items():
        s = code_summary(w)
        print(f"  {name}: alphabet={s['alphabet_size']} codon_len={s['codon_length']} "
              f"determining={s['determining_positions']} silent={s['silent_positions']} "
              f"H/P={s['n_H_codons']}/{s['n_P_codons']} ({s['actual_h_fraction']:.0%} H)")

    # Sanity: translation + silent-position check on pos1_only.
    print("\nSilent-position sanity (pos1_only — only the middle position matters):")
    w = cat["pos1_only"]
    # two codons differing only in silent positions must map to same residue
    import itertools
    same = 0; diff = 0
    for c in itertools.product(range(4), repeat=3):
        # vary silent positions 0 and 2, hold pos1
        base = w.code[c]
        for v0 in range(4):
            for v2 in range(4):
                c2 = (v0, c[1], v2)
                if w.code[c2] == base:
                    same += 1
                else:
                    diff += 1
    print(f"  codons sharing pos1 map to same residue: {same} consistent, {diff} violations")
